import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, SIZES, SHADOWS } from '../constants/theme';

const { width } = Dimensions.get('window');

export const welcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  gradientTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 400,
  },
  gridOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.2,
  },
  gridRow: {
    flexDirection: 'row',
  },
  gridCell: {
    width: 40,
    height: 40,
    borderWidth: 0.5,
  },
  curvedLineContainer: {
    position: 'absolute',
    top: 450,
    left: 0,
    right: 0,
    height: 60,
    zIndex: 1,
  },
  contentContainer: {
    flex: 1,
  },
  transactionsContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 90,
    paddingHorizontal: SIZES.padding,
  },
  transactionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: SIZES.radius + 2,
    padding: 16,
    marginVertical: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    position: 'relative',
    overflow: 'hidden',
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SIZES.paddingSmall + 2,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  transactionInfo: {
    flex: 1,
    marginRight: SIZES.paddingSmall,
  },
  transactionTitle: {
    color: '#111827',
    fontSize: SIZES.fontSmall + 1,
    fontWeight: '600',
    marginBottom: 2,
  },
  transactionSubtitle: {
    color: '#6B7280',
    fontSize: SIZES.fontTiny + 1,
    marginTop: 0,
  },
  transactionAmount: {
    alignItems: 'flex-end',
  },
  transactionValue: {
    fontSize: SIZES.fontSmall + 1,
    fontWeight: '700',
    marginBottom: 1,
  },
  transactionTime: {
    fontSize: SIZES.fontTiny + 1,
    color: '#6B7280',
  },
  transactionDate: {
    color: '#10B981',
    fontSize: SIZES.fontTiny,
    marginTop: 2,
    fontWeight: '500',
  },
  bottomContainer: {
    marginBottom: 20,
    width: '100%',
    paddingHorizontal: SIZES.padding,
  },
  carousel: {
    width: width,
    marginLeft: -SIZES.padding,
  },
  slide: {
    width: width,
    paddingHorizontal: SIZES.padding,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  headerText: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 30,
    flex: 1,
  },
  highlightBox: {
    backgroundColor: '#1C1C1E',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    shadowColor: '#1C1C1E',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  highlightText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  subHeaderText: {
    color: '#6B7280',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 10,
  },
  paginationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 30,
  },
  paginationDot: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1C1C1E',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 16,
    gap: 12,
  },
  signInButton: {
    flex: 0.48,
    height: SIZES.buttonHeight,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.radius,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  signInButtonText: {
    color: '#1A1A1A',
    fontWeight: '600',
    fontSize: SIZES.fontMedium,
  },
  signUpButtonContainer: {
    flex: 0.48,
    height: SIZES.buttonHeight,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    shadowColor: '#1C1C1E',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  signUpButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.radius,
    backgroundColor: '#1C1C1E',
  },
  signUpButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: SIZES.fontMedium,
    marginRight: 8,
  },
  arrowContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
